### ISSUE TITLE
Attempted import error: 'useHistory' is not exported from 'react-router'

### ISSUE THREAD

**Issue by ollieSk8** [alibaba/hooks#1094]
请问 use-url-state 不支持 react-route 6么？react-route版本^6.0.0-beta.0,@ahooksjs/use-url-state版本 ^2.5.8
<img width="924" alt="截屏2021-08-02 下午4 27 33" src="https://user-images.githubusercontent.com/9378275/127829250-8c89f90f-b3a8-433e-b36d-d436199c5608.png">

**Comment by brickspert** [comment]
暂时不支持 v6 版本

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

**Comment by ArtemFokin** [comment]
I'm still gettings this error:
Failed to compile.
./node_modules/@ahooksjs/use-url-state/es/index.js
Attempted import error: 'useHistory' is not exported from 'react-router' (imported as 'rc').

"@ahooksjs/use-url-state": "^3.0.0-alpha.14",
"ahooks": "^3.0.0-alpha.14",
"react-router-dom": "^6.0.2",
"react": "^17.0.2",


i'm also tried implement it in codesandbox
https://codesandbox.io/s/xenodochial-cloud-pg1lw
but it works well...

maybe some webpack error or vscode

**Comment by brickspert** [comment]
> I'm still gettings this error: Failed to compile. ./node_modules/@ahooksjs/use-url-state/es/index.js Attempted import error: 'useHistory' is not exported from 'react-router' (imported as 'rc').
> 
> "@ahooksjs/use-url-state": "^3.0.0-alpha.14", "ahooks": "^3.0.0-alpha.14", "react-router-dom": "^6.0.2", "react": "^17.0.2",
> 
> i'm also tried implement it in codesandbox https://codesandbox.io/s/xenodochial-cloud-pg1lw but it works well...
> 
> maybe some webpack error or vscode

Sure, this is a known waring, I will fix it. 

but you can use it normally now。

**Comment by brickspert** [comment]
> I'm still gettings this error: Failed to compile. ./node_modules/@ahooksjs/use-url-state/es/index.js Attempted import error: 'useHistory' is not exported from 'react-router' (imported as 'rc').
> 
> "@ahooksjs/use-url-state": "^3.0.0-alpha.14", "ahooks": "^3.0.0-alpha.14", "react-router-dom": "^6.0.2", "react": "^17.0.2",
> 
> i'm also tried implement it in codesandbox https://codesandbox.io/s/xenodochial-cloud-pg1lw but it works well...
> 
> maybe some webpack error or vscode

We have fixed this warning on v3.0.0-alpha.15
